name: .NET

on: [push]
jobs:
  build:
    runs-on: windows-2019
    permissions:
      contents: read
      id-token: write # For federated auth
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1
    - name: Generate NuGet Cache Key
      id: nuget_cache_key
      run: powershell -Command Write-Host "::set-output name=key::nuget-cache-$((Get-FileHash -InputStream ([IO.MemoryStream]::new([Text.Encoding]::UTF8.GetBytes((Select-String -Path "*/*.csproj" -Pattern "PackageReference" | foreach {$_.line.Trim()} | Sort-Object))))).Hash)"
    - name: Cache Nuget
      uses: actions/cache@v3
      with:
        key: ${{ steps.nuget_cache_key.outputs.key }}
        path: ~/.nuget/packages
    - name: Restore dependencies
      run: msbuild /p:Configuration=Release -t:restore DedicatedServerWrapper.sln
    - name: Build Shared
      run: msbuild /p:Configuration=Release Meds.Shared/Meds.Shared.csproj
    - name: Build Manager
      run: msbuild /p:Configuration=Release Meds.Watchdog/Meds.Watchdog.csproj
    - name: Generate ME cache key
      id: me_cache_key
      run: powershell -Command Write-Host "::set-output name=key::me-cache-v1-$(Get-Date -Format yyyy-MM)"
    - name: Cache ME
      uses: actions/cache@v3
      with:
        key: ${{ steps.me_cache_key.outputs.key }}
        restore-keys: |
          me-cache-v1-
        path: Meds.Wrapper/GameInstall/
    - name: Install ME
      run: Meds.Watchdog/bin/Release/Meds.Watchdog.exe restore-game-binaries Meds.Wrapper/GameInstall/ communityedition
    - name: Build wrapper
      run: msbuild /p:Configuration=Release Meds.Wrapper/Meds.Wrapper.csproj
    - name: Upload Watchdog
      uses: actions/upload-artifact@v2
      with:
        name: meds-watchdog
        path: Meds.Watchdog/bin/Release
    - name: Upload Wrapper
      uses: actions/upload-artifact@v2
      with:
        name: meds-wrapper
        path: Meds.Wrapper/bin/Release
    - name: Log into gcloud
      id: auth
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/445692247363/locations/global/workloadIdentityPools/github-actions/providers/github-actions'
        service_account: 'meds-release-uploader@machpi-net.iam.gserviceaccount.com '
    - name: Upload Wrapper Release
      uses: 'google-github-actions/upload-cloud-storage@v1'
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      with:
        path: Meds.Wrapper/bin/Release
        destination: "meds-dist/${{github.ref}}/wrapper"
        parent: false
