name: .NET

on: [push]
jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.1.1
    - name: Generate NuGet Cache Key
      id: nuget_cache_key
      run: powershell -Command Write-Host "::set-output name=key::nuget-cache-$((Get-FileHash -InputStream ([IO.MemoryStream]::new([Text.Encoding]::UTF8.GetBytes((Select-String -Path "*/*.csproj" -Pattern "PackageReference" | foreach {$_.line.Trim()} | Sort-Object))))).Hash)"
    - name: Cache Nuget
      uses: actions/cache@v2.1.4
      with:
        key: ${{ steps.nuget_cache_key.outputs.key }}
        path: ~/.nuget/packages
    - name: Restore dependencies
      run: msbuild /p:Configuration=Release -t:restore DedicatedServerWrapper.sln
    - name: Build FlatBuffers
      run: msbuild /p:Configuration=Release Meds.Shared/Meds.Shared.csproj /t:FlatcCompile
    - name: Build Shared
      run: msbuild /p:Configuration=Release Meds.Shared/Meds.Shared.csproj
    - name: Build Manager
      run: msbuild /p:Configuration=Release Meds.Watchdog/Meds.Watchdog.csproj
    - name: Generate ME cache key
      id: me_cache_key
      run: powershell -Command Write-Host "::set-output name=key::me-cache-v1-$(Get-Date -Format yyyy-MM)"
    - name: Cache ME
      uses: actions/cache@v2.1.4
      with:
        key: ${{ steps.me_cache_key.outputs.key }}
        path: Meds.Wrapper/GameInstall/
    - name: Install ME
      run: Meds.Watchdog/bin/Release/Meds.Watchdog.exe restore-game-binaries Meds.Wrapper/GameInstall/ communityedition
    - name: Build wrapper
      run: dir /b /a /s
    - name: Build wrapper
      run: msbuild /p:Configuration=Release Meds.Wrapper/Meds.Wrapper.csproj
    - name: Upload Watchdog
      uses: actions/upload-artifact@v2
      with:
        name: meds-watchdog
        path: Meds.Watchdog/bin/Release
    - name: Upload Wrapper
      uses: actions/upload-artifact@v2
      with:
        name: meds-wrapper
        path: Meds.Wrapper/bin/Release
    - name: Upload Wrapper Release
      uses: google-github-actions/upload-cloud-storage@v0.2.0
      if: github.ref == 'refs/heads/develop' || contains(github.ref, 'refs/tags/')
      with:
        credentials: ${{ secrets.RELEASE_UPLOAD_KEY }}
        path: Meds.Wrapper/bin/Release
        destination: "meds-dist/${{github.ref}}/wrapper"
